// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4Assignment_ZM.Models;

namespace Mission4Assignment_ZM.Migrations
{
    [DbContext(typeof(MovieAppContext))]
    [Migration("20220127043929_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4Assignment_ZM.Models.MovieAdd", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Title");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            Title = "Inception",
                            Category = "Action",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "Best Movie EVER!",
                            Rating = "PG-13",
                            Year = "2010"
                        },
                        new
                        {
                            Title = "Rudy",
                            Category = "Drama",
                            Director = "David Anspaugh",
                            Edited = false,
                            LentTo = "",
                            Notes = "Gave me chills",
                            Rating = "PG-13",
                            Year = "1993"
                        },
                        new
                        {
                            Title = "The Lion King",
                            Category = "Family",
                            Director = "Roger Allers",
                            Edited = false,
                            LentTo = "",
                            Notes = "SO inspirational",
                            Rating = "G",
                            Year = "1994"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
